"""Setup and first-run configuration helpers for familiar-ai.

This module provides:
- `SetupConfig`: unified config schema shared by setup wizard and GUI settings
- `generate_env_file()`: write a clean `.env` from `SetupConfig`
- `save_setup_config()`: merge/persist settings into an existing `.env`
- `migrate_legacy_env_file()`: add unified keys for legacy `ANTHROPIC_*` env files
- `run_cli_setup_wizard()`: minimal terminal setup fallback when GUI is unavailable
- camera validation / ONVIF discovery helpers
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from dotenv import dotenv_values, set_key, unset_key

from .settings_schema import SetupConfig, setup_config_to_env_values

logger = logging.getLogger(__name__)


_ANTHROPIC_KEY_RE = re.compile(r"^sk-ant-")
_SENSITIVE_KEYS = frozenset(
    {
        "API_KEY",
        "ELEVENLABS_API_KEY",
        "CAMERA_PASSWORD",
        "UTILITY_API_KEY",
        "SCENE_API_KEY",
        "CAMERA_PTZ_PASSWORD",
    }
)


def is_first_run(env_dir: Path | None = None) -> bool:
    """Return True if no .env file exists in *env_dir* (defaults to cwd)."""
    base = env_dir or Path.cwd()
    return not (base / ".env").exists()


def _bool_to_env(value: bool) -> str:
    return "true" if value else "false"


def generate_env_file(config: SetupConfig, path: Path | None = None) -> Path:
    """Write a clean `.env` file from *config* and return the written path."""
    env_path = path or Path.cwd() / ".env"
    env_path.parent.mkdir(parents=True, exist_ok=True)

    values = setup_config_to_env_values(config)
    lines = [
        "# familiar-ai configuration — generated by setup",
        "# Edit this file to change settings, then restart.",
        "",
    ]
    for key, value in values.items():
        if value == "":
            continue
        lines.append(f"{key}={value}")
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return env_path


def save_setup_config(
    config: SetupConfig,
    path: Path | None = None,
    *,
    preserve_empty_sensitive: bool = True,
) -> Path:
    """Persist setup/config values into an existing `.env`.

    Blank non-sensitive values remove the key. Blank sensitive values are preserved
    by default so a masked GUI field does not accidentally wipe a stored secret.
    """
    env_path = path or Path.cwd() / ".env"
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.touch(exist_ok=True)
    env_str = str(env_path)

    for key, value in setup_config_to_env_values(config).items():
        if value:
            set_key(env_str, key, value, quote_mode="never")
            continue
        if preserve_empty_sensitive and key in _SENSITIVE_KEYS:
            continue
        unset_key(env_str, key)

    return env_path


def migrate_legacy_env_file(path: Path | None = None) -> tuple[bool, list[str]]:
    """Add unified keys for legacy Anthropic-only env files.

    Keeps old keys in place for compatibility, but writes the new keys so the rest
    of the app can consistently use PLATFORM/API_KEY/MODEL.
    """
    env_path = path or Path.cwd() / ".env"
    if not env_path.exists():
        return False, []

    values = dotenv_values(env_path)
    updates: dict[str, str] = {}
    notes: list[str] = []

    legacy_api_key = str(values.get("ANTHROPIC_API_KEY") or "").strip()
    legacy_model = str(values.get("ANTHROPIC_MODEL") or "").strip()
    platform = str(values.get("PLATFORM") or "").strip()
    api_key = str(values.get("API_KEY") or "").strip()
    model = str(values.get("MODEL") or "").strip()

    if legacy_api_key and not api_key:
        updates["API_KEY"] = legacy_api_key
        notes.append("Migrated ANTHROPIC_API_KEY -> API_KEY")
    if legacy_model and not model:
        updates["MODEL"] = legacy_model
        notes.append("Migrated ANTHROPIC_MODEL -> MODEL")
    if (legacy_api_key or legacy_model) and not platform:
        updates["PLATFORM"] = "anthropic"
        notes.append("Set PLATFORM=anthropic for legacy Anthropic config")

    if not updates:
        return False, []

    env_str = str(env_path)
    for key, value in updates.items():
        set_key(env_str, key, value, quote_mode="never")
    return True, notes


def validate_anthropic_key(key: str) -> tuple[bool, str]:
    """Check Anthropic API key format. Returns (ok, error_message)."""
    if not key:
        return False, "API key cannot be empty"
    if not _ANTHROPIC_KEY_RE.match(key):
        return False, "Anthropic API keys must start with 'sk-ant-'"
    return True, ""


def run_cli_setup_wizard(env_path: Path) -> bool:
    """Minimal terminal setup fallback when no GUI is requested."""
    print("familiar-ai first-run setup")
    print(f"Configuration file: {env_path}")
    print("Press Enter to keep the default value shown in brackets.")

    platform = input("Platform [anthropic/gemini/openai/kimi/glm/cli] (anthropic): ").strip()
    api_key = input("API key: ").strip()
    model = input("Model [optional]: ").strip()

    if not api_key:
        print("Setup aborted: API key is required.")
        return False

    config = SetupConfig(
        platform=platform or "anthropic",
        api_key=api_key,
        model=model,
    )
    generate_env_file(config, path=env_path)
    print(f"Saved configuration to {env_path}")
    return True


try:
    from onvif import ONVIFCamera  # type: ignore[import]
except ImportError:

    class ONVIFCamera:  # type: ignore[no-redef]
        """Stub when onvif-zeep-async is not installed."""

        def __init__(self, *args: Any, **kwargs: Any) -> None:
            raise ImportError(
                "onvif-zeep-async is required for camera support. "
                "Install with: pip install 'familiar-ai[camera]'"
            )

        def create_devicemgmt_service(self) -> None:
            pass


async def validate_camera_connection(
    host: str, username: str, password: str, port: int = 2020
) -> tuple[bool, str]:
    """Test ONVIF connectivity. Returns (ok, error_message)."""
    try:
        cam = ONVIFCamera(host, port, username, password)
        cam.create_devicemgmt_service()
        return True, ""
    except Exception as exc:
        return False, str(exc)


async def _ws_discover() -> list[Any]:
    """Run ONVIF WS-Discovery and return raw service objects."""
    try:
        import asyncio
        from wsdiscovery import WSDiscovery  # type: ignore[import]

        def _sync() -> list[Any]:
            wsd = WSDiscovery()
            wsd.start()
            svcs = wsd.searchServices()
            wsd.stop()
            return svcs

        return await asyncio.to_thread(_sync)
    except ImportError:
        logger.debug("wsdiscovery not available — camera auto-discovery disabled")
        return []


async def discover_onvif_cameras(timeout: float = 3.0) -> list[dict[str, str]]:
    """Scan the local network for ONVIF cameras via WS-Discovery."""
    import asyncio

    try:
        services = await asyncio.wait_for(_ws_discover(), timeout=timeout)
    except Exception as exc:
        logger.debug("Camera discovery error: %s", exc)
        return []

    results: list[dict[str, str]] = []
    for svc in services:
        try:
            addrs = svc.getXAddrs()
            if not addrs:
                continue
            parsed = urlparse(addrs[0])
            host = parsed.hostname or ""
            if host:
                results.append({"host": host, "address": addrs[0]})
        except Exception:
            continue
    return results
